import { expect, test } from '@playwright/test'

test('renders dynamic metrics, five executive lenses, language and mobile layout', async ({ page }) => {
  test.setTimeout(120000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.brand')).toContainText('SignalPath')
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await expect(page.locator('.decision-lab').getByRole('tab')).toHaveCount(5)
  await expect(page.locator('.decision-lab')).toContainText('Change drivers')
  await page.getByRole('tab', { name: 'Efficiency' }).click()
  await expect(page.locator('.decision-lab')).toContainText('Sessions per user')
  await page.getByRole('tab', { name: 'Stability' }).click()
  await expect(page.locator('.decision-lab')).toContainText('coefficient of variation')
  const before=await page.locator('.metric-card strong').first().innerText()
  await page.locator('.period-options').getByRole('button', { name: '7 days' }).click()
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await expect.poll(()=>page.locator('.metric-card strong').first().innerText()).not.toBe(before)
  await page.getByRole('button',{name:'PT'}).click()
  await expect(page.getByText('Escopo da análise')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('uses a distinct page contract and five distinct lenses for every secondary page', async ({ page }) => {
  test.setTimeout(180000)
  await page.goto('/')
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  const pages=page.locator('header nav button')
  const titles=new Set<string>(),series=new Set<string>()
  for(let index=1;index<await pages.count();index+=1){
    await pages.nth(index).click()
    await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
    await expect(page.locator('.query-error')).toHaveCount(0)
    const lab=page.locator('.secondary-lab')
    const tabs=lab.getByRole('tab')
    await expect(tabs).toHaveCount(5)
    const states=new Set<string>()
    for(let tab=0;tab<5;tab+=1){
      await tabs.nth(tab).click()
      states.add(await lab.locator('.page-lens-content').innerText())
    }
    expect(states.size).toBe(5)
    titles.add(await page.locator('.page-head h1').innerText())
    series.add(String(await page.locator('.analysis-grid .chart-viewport').first().getAttribute('data-series-signature')))
  }
  expect(titles.size).toBe(5)
  expect(series.size).toBeGreaterThan(2)
})

test('labels full history without inventing a prior window', async ({ page }) => {
  test.setTimeout(120000)
  await page.goto('/')
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await page.locator('.period-options').getByRole('button', { name: 'History' }).click()
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await expect(page.locator('.metric-card .delta.neutral').first()).toContainText('no complete prior window')
})

test('keeps full-source funnel stages explicit and filtered purchaser behavior separate', async ({ page }) => {
  test.setTimeout(120000)
  await page.goto('/')
  await page.getByRole('button',{name:'Journey Evidence'}).click()
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await expect(page.locator('.secondary-lab')).toContainText('full-source')
  await expect(page.locator('.panel.detail')).toContainText('Full-source reference')
  await expect(page.locator('.analysis-grid .panel').first()).toContainText('Purchasers over time')
})

test('loads only compact marts and shares the item revenue authority', async ({ page }) => {
  test.setTimeout(120000)
  const requests:string[]=[]
  page.on('request',request=>{if(request.url().includes('mart_growth_products.parquet'))requests.push(request.url())})
  await page.goto('/')
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  expect(requests.length).toBeGreaterThan(0)
  await page.getByRole('button',{name:'Product Performance'}).click()
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  expect(requests.length).toBeGreaterThan(0)
})

test('reconciles displayed revenue and sessions and verifies responsive renders', async ({ page }) => {
  test.setTimeout(120000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await expect(page.locator('.metric-card strong').nth(1)).toHaveText('116,075')
  await expect(page.locator('.metric-card strong').last()).toHaveText('$56,324')
  await expect(page.locator('.scope-caption')).toContainText('2021-01-02')
  await page.screenshot({ path:'test-results/audit-desktop.png', fullPage:true })
  await page.getByRole('button',{name:'Product Performance'}).click()
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await expect(page.locator('.metric-card strong').last()).toHaveText('$56,324')
  await page.getByRole('button',{name:'Journey Evidence'}).click()
  await page.locator('.decision-strip:not(.is-loading)').waitFor({ timeout: 90000 })
  await page.setViewportSize({ width:390,height:844 })
  await page.waitForTimeout(500)
  expect(await page.evaluate(()=>Array.from(document.querySelectorAll('.chart-viewport')).every(el=>{const rect=el.getBoundingClientRect();return rect.left>=0&&rect.right<=window.innerWidth+1}))).toBe(true)
  await page.screenshot({ path:'test-results/audit-mobile.png',fullPage:true })
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('never shows baseline KPIs when mart access fails',async({page})=>{
  test.setTimeout(120000)
  await page.route('**/mart_growth_sessions.parquet',route=>route.abort())
  await page.goto('/')
  await expect(page.locator('.query-error')).toBeVisible({timeout:90000})
  await expect(page.locator('.metric-card')).toHaveCount(0)
  await expect(page.locator('.decision-lab')).toHaveCount(0)
})
test('returns to the top when changing dashboard pages',async({page})=>{
  await page.goto('/')
  await page.locator('.decision-strip:not(.is-loading)').waitFor({timeout:90000})
  await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight))
  expect(await page.evaluate(()=>window.scrollY)).toBeGreaterThan(0)
  await page.getByRole('button',{name:'Journey Evidence'}).click()
  await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0)
})
